import { GoogleGenAI } from "@google/genai";

const GEMINI_MODELS = {
  DEFAULT: "gemini-2.5-flash",
  FALLBACKS: [
    "gemini-2.5-flash",
    "gemini-3.5-flash",
    "gemini-3.6-flash",
    "gemini-flash-latest",
    "gemini-3.5-flash-lite",
  ],
};

const DEFAULT_AI_CONFIG = {
  temperature: 0.4,
  topP: 0.95,
  maxOutputTokens: 2048,
};

/**
 * Vercel Serverless Function: POST /api/generate
 * Executes securely on the server, keeping API keys hidden from the browser.
 * Supports text and multimodal image/OCR payloads.
 */
export default async function handler(req, res) {
  // Only allow POST requests
  if (req.method !== "POST") {
    res.setHeader("Allow", ["POST"]);
    return res.status(405).json({ error: `Method ${req.method} Not Allowed` });
  }

  const apiKey = process.env.GEMINI_API_KEY || process.env.VITE_GEMINI_API_KEY;

  if (!apiKey) {
    console.error("GEMINI_API_KEY is not configured in server environment variables.");
    return res.status(500).json({ error: "Server AI configuration error. API key missing." });
  }

  const {
    prompt,
    image, // { data: string (base64), mimeType: string }
    model = GEMINI_MODELS.DEFAULT,
    systemInstruction,
    config = {},
  } = req.body || {};

  if (!prompt || typeof prompt !== "string") {
    return res.status(400).json({ error: "A valid 'prompt' string is required." });
  }

  const ai = new GoogleGenAI({ apiKey });

  const generationConfig = {
    ...DEFAULT_AI_CONFIG,
    ...config,
  };

  if (systemInstruction) {
    generationConfig.systemInstruction = systemInstruction;
  }

  // Construct multimodal or text contents
  let contents = prompt;
  if (image && image.data) {
    contents = [
      {
        text: prompt,
      },
      {
        inlineData: {
          mimeType: image.mimeType || "image/jpeg",
          data: image.data,
        },
      },
    ];
  }

  // Attempt generation with primary model
  try {
    const response = await ai.models.generateContent({
      model,
      contents,
      config: generationConfig,
    });

    const text = response?.text || "No response generated by the AI model.";
    return res.status(200).json({ text });
  } catch (primaryError) {
    console.warn(`Primary model "${model}" failed: ${primaryError.message}. Attempting fallback models...`);

    // Try fallback models if primary model fails
    for (const fallbackModel of GEMINI_MODELS.FALLBACKS) {
      if (fallbackModel === model) continue;

      try {
        const fallbackResponse = await ai.models.generateContent({
          model: fallbackModel,
          contents,
          config: generationConfig,
        });

        if (fallbackResponse?.text) {
          console.info(`Successfully recovered using fallback model: ${fallbackModel}`);
          return res.status(200).json({
            text: fallbackResponse.text,
            fallbackUsed: fallbackModel,
          });
        }
      } catch (fallbackError) {
        console.warn(`Fallback model "${fallbackModel}" failed: ${fallbackError.message}`);
      }
    }

    // If all models fail
    console.error("All AI models failed to generate content:", primaryError);
    return res.status(502).json({
      error: "Failed to generate AI response from upstream provider.",
      details: primaryError.message,
    });
  }
}
