import { GEMINI_MODELS, DEFAULT_AI_CONFIG } from "../constants/ai.constants.js";

/**
 * Robust AI content generation helper that securely calls the backend /api/generate endpoint.
 * This ensures that API keys are NEVER exposed in the client-side bundle or network tab.
 *
 * @param {Object} options
 * @param {string} options.prompt - The input prompt text for the AI.
 * @param {string} [options.model=GEMINI_MODELS.DEFAULT] - The target Gemini model name.
 * @param {string} [options.systemInstruction] - Optional system instructions/persona.
 * @param {Object} [options.config] - Optional overrides for generation parameters (temperature, maxOutputTokens, etc.)
 * @returns {Promise<string>} Generated text response.
 */
export async function generateAIResponse({
  prompt,
  model = GEMINI_MODELS.DEFAULT,
  systemInstruction,
  config = {}
}) {
  if (!prompt || typeof prompt !== "string") {
    throw new Error("A valid prompt string is required for AI generation.");
  }

  const payload = {
    prompt,
    model,
    systemInstruction,
    config: {
      ...DEFAULT_AI_CONFIG,
      ...config,
    },
  };

  try {
    const response = await fetch("/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const errorMessage =
        errorData.error ||
        errorData.details ||
        `AI Server Error (Status ${response.status}): ${response.statusText}`;
      console.error("Serverless AI generation error:", errorMessage);
      throw new Error(errorMessage);
    }

    const data = await response.json();
    return data.text || "No response generated by the AI model.";
  } catch (error) {
    console.error("Failed to generate AI response via /api/generate:", error);
    throw error;
  }
}
