import { GoogleGenAI } from "@google/genai";
import { GEMINI_MODELS, FALLBACK_MODELS, DEFAULT_AI_CONFIG } from "../constants/ai.constants.js";

const API_KEY = import.meta.env.VITE_GEMINI_API_KEY || "";

/**
 * Centralized Google GenAI Client Instance
 */
export const ai = new GoogleGenAI({ apiKey: API_KEY });

/**
 * Robust AI content generation helper with automatic fallback model recovery.
 *
 * @param {Object} options
 * @param {string} options.prompt - The input prompt text for the AI.
 * @param {string} [options.model=GEMINI_MODELS.DEFAULT] - The target Gemini model name.
 * @param {string} [options.systemInstruction] - Optional system instructions/persona.
 * @param {Object} [options.config] - Optional overrides for generation parameters (temperature, maxOutputTokens, etc.)
 * @returns {Promise<string>} Generated text response.
 */
export async function generateAIResponse({
  prompt,
  model = GEMINI_MODELS.DEFAULT,
  systemInstruction,
  config = {}
}) {
  if (!API_KEY) {
    console.error("Gemini API Key (VITE_GEMINI_API_KEY) is missing or undefined.");
    throw new Error("Gemini API key is not configured.");
  }

  const generationConfig = {
    ...DEFAULT_AI_CONFIG,
    ...config,
  };

  if (systemInstruction) {
    generationConfig.systemInstruction = systemInstruction;
  }

  // Attempt generation with requested model first
  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: generationConfig,
    });

    if (response && response.text) {
      return response.text;
    }
    return "No response generated by the AI model.";
  } catch (primaryError) {
    console.warn(`Primary model "${model}" failed: ${primaryError.message}. Attempting fallback models...`);

    // Try fallback models if primary model is unavailable or encounters temporary limits
    for (const fallbackModel of FALLBACK_MODELS) {
      if (fallbackModel === model) continue;

      try {
        const fallbackResponse = await ai.models.generateContent({
          model: fallbackModel,
          contents: prompt,
          config: generationConfig,
        });

        if (fallbackResponse && fallbackResponse.text) {
          console.info(`Successfully recovered using fallback model: ${fallbackModel}`);
          return fallbackResponse.text;
        }
      } catch (fallbackError) {
        console.warn(`Fallback model "${fallbackModel}" failed: ${fallbackError.message}`);
      }
    }

    // If all models fail, rethrow original error to caller
    throw primaryError;
  }
}
